services:
  psql_prod:
    container_name: psql_prod_lab
    image: postgres:16.3-alpine3.19
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
    # - ~/Desktop/db-data:/var/lib/postgresql/data
      - prod_data:/var/lib/postgresql/data
    networks:
      - prod_network    

  spring-store:
    container_name: spring-store-api
    image: ecfcode/spring-store:0.0.5
    ports:
      - "8080:8080"
    networks:
      - prod_network
    depends_on:
      - psql_prod
  
networks:
  prod_network:
    driver: bridge

volumes:
  dev_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/Documents/Database/Postgres/dev_data

  prod_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/Documents/Database/Postgres/prod_data/  