services:
  postgres:
    container_name: postgres-lab
    image: postgres:16.3-alpine3.19
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
    # - ~/Desktop/db-data:/var/lib/postgresql/data
      - lab-data:/var/lib/postgresql/data
    networks:
      - lab-network
  spring-store:
    container_name: spring-store-api
    image: spring-store/spring-store:0.0.4
    ports:
      - "8080:8080"
    networks:
      - lab-network
    depends_on:
      - postgres
  
networks:
  lab-network:
    driver: bridge

volumes:
  lab-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/Documents/Database/Postgres/db-data/